[[redirects]]
  from = "/officiel"
  to   = "https://officiel-bsd.netlify.app/officiel/"
  status = 200
[[redirects]]
  from = "/officiel/*"
  to = "https://officiel-bsd.netlify.app/officiel/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
